# Generated by Django 4.1.2 on 2022-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_input', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('stop_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meditation_type', models.CharField(choices=[('mindfullness', 'mindfullness'), ('visualization', 'visaualization'), ('mantra', 'mantra'), ('movement', 'meditaion')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.CharField(choices=[('ocean sound', 'ocean sound'), ('birds sound', 'birds sound'), ('nature sound', 'nature sound')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.DeleteModel(
            name='Meditation',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
