# Generated by Django 4.1.2 on 2022-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_registration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_down',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.TimeField()),
            ],
        ),
    ]
