# Generated by Django 4.1.1 on 2022-10-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_count_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
