# Generated by Django 4.1.2 on 2022-10-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_register_client_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_name',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
