# Generated by Django 4.1 on 2022-10-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_0004_chatbot_0006_login_register_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBot',
        ),
    ]
