# Generated by Django 4.1.2 on 2022-10-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='count_down',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solaceapp.countdowntimer'),
        ),
    ]
