# Generated by Django 4.1.2 on 2022-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meditation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
