# Generated by Django 4.1.2 on 2022-10-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaceapp', '0002_delete_meditation_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meditation_type', models.CharField(choices=[('mindfullness', 'mindfullness'), ('visualization', 'visaualization'), ('mantra', 'mantra'), ('movement', 'meditaion')], max_length=50, null=True)),
                ('count_down_timer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solaceapp.countdowntimer')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solaceapp.music')),
            ],
        ),
    ]
