# Generated by Django 4.1.2 on 2022-10-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solaceapp', '0002_meditation_count_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='mindfullness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solaceapp.music'),
        ),
    ]
