# Generated by Django 4.1.2 on 2022-10-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solaceapp', '0003_meditation_mindfullness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meditation',
            old_name='mindfullness',
            new_name='music',
        ),
    ]
