# Generated by Django 4.1.2 on 2022-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaceapp', '0003_meditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='1234', max_length=15),
        ),
    ]
